const express=require("express")
const Router=express.Router()
const user=require("./User/usercontroller")
const journalist=require("./Journalist/journalistcontroller")
const news=require("./News/newscontroller")

Router.post("/userreg",user.userreg)
Router.post("/userlogin",user.userlogin)
Router.post("/forgotpassword",user.forgotPassword)
Router.post("/userview",user.userview)
Router.post("/viewalluser",user.viewalluser)
Router.post("/viewuserid/:id",user.viewuserid)
Router.post("/deleteuser/:id",user.deleteuser)

Router.post("/journalistreg",journalist.upload,journalist.journalistreg)
Router.post("/journalistlogin",journalist.journalistlogin)
Router.post("/forgotpassword",journalist.forgotPassword)
Router.post("/journalistview",journalist.journalistview)
Router.post("/viewalljournalistReqs",journalist.viewalljournalistReqs)
Router.post("/viewapprovedjournalist",journalist.viewapprovedjournalist)
Router.post("/viewjournalistid/:id",journalist.viewjournalistid)
Router.post("/deletejournalist/:id",journalist.deletejournalist)
Router.post("/approvejournalist/:id",journalist.approvejournalist)
Router.post("/editjournalist/:id",journalist.upload,journalist.editjournalist)

Router.post("/newsadd",journalist.upload,news.newsadd)
Router.post("/viewallnews",news.viewallnews)
Router.delete("/deletenews/:id",news.deletenews)
Router.post("/viewunsavenews",news.viewunsavenews)
Router.post("/savenews/:id",news.savenews)
Router.post("/viewsavenews",news.viewsavenews)
Router.post("/pdeletenews/:id",news.pdeletenews)
Router.get("/viewnewsid/:id",news.viewnewsid)
Router.get("/viewnewsbyid/:id",news.viewnewsbyid)
module.exports=Router